function fsignal = prep_hpfilter(signal,order,fc,fs)
%PREP_HPFILTER Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.14 and the Signal Processing Toolbox 6.17.
% Butterworth Highpass filter designed using FDESIGN.LOWPASS.
% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.highpass('N,F3dB', order, fc, fs);
Hd = design(h, 'butter');
[b a] = sos2tf(Hd.sosMatrix,Hd.scaleValues);
%fsignal = filtfilt(b,a,signal);
fsignal = filtfilt(b,a,signal);
% [EOF]
return
